### ISSUE TITLE
Key not present in Dictionary: buffer

### ISSUE THREAD

**Issue by drzel** [tmux-plugins/vim-tmux#21] opened 2018-01-23 07:30 UTC
I get the following error when opening ~/.tmux.conf in neovim.

```
Error detected while processing /Users/sheldon/.local/share/nvim/plugged/vim-tmux/ftplugin/tmux.vim:
line   14:
E716: Key not present in Dictionary: buffer
E15: Invalid expression: empty(s:map_dict) && ! s:map_dict['buffer']
```
Seems to be caused by the change in: 09499a87e2859269d07e461006a113f0b7dc105b

**Comment by bruno-** [comment] 2018-01-23 16:30
I don't use or have neovim installed. Anyone can help debug this?
I think we'd want to avoid executing this code branch if neovim is used https://github.com/tmux-plugins/vim-tmux/commit/09499a87e2859269d07e461006a113f0b7dc105b#diff-bec167678d215f2cba1a9f14e3cbdedcR12

**Comment by benknoble** [comment] 2018-01-23 22:48
Can reproduce in regular (terminal) vim

**Comment by upsetbit** [comment] 2018-01-24 08:12
Hello, Bruno.

Firstly, thank you for all the effort put in this project.

I'm currently using Vim 8.0 and have stumbled upon the same problem. To test it out, I "turned it off" everything on my `.vimrc`, except the plugin. The error message was the same.

More info on version: 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 23 2017 02:04:34)
Included patches: 1-1331
Compiled by Caian R. Ertl
Huge version with X11-Athena GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           -netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        +xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
-dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
```

**Comment by benknoble** [comment] 2018-01-24 11:26
Mine as well: I suspect it's an error in the logic of detecting the map to `K`

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  8 2018 13:55:49)
macOS version
Included patches: 1-1400
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.5.0 -lobjc    
```

**Comment by bruno-** [comment] 2018-01-24 12:14
Hi guys,

I was able to reproduce the issue with vim. It was caused by the latest commit that is now reverted. The issue should be fixed now.

**Closed as completed by bruno-** 2018-01-24 12:14 UTC
