### ISSUE TITLE
Requesting ability to configure the Shift+K bind override

### ISSUE THREAD

**Issue by unphased** [tmux-plugins/vim-tmux#1] opened 2015-01-24 20:28 UTC
I have an action bound to `K` in Vim (Move down 7 lines), and I use it a lot. 

I also really like the vim-tmux syntax highlighting for my tmux config. However I have not come up with a nice way to remove the binding because it will be reinstated every time that vim-tmux updates itself via `tpm`.

Any ideas? Is there a way to use `~/.vim/after/vim-tmux.vim` or something? I tried it but it didn't work for some reason. 

I can obviously fork and change but then I would have to manually update this plugin.

**Comment by bruno-** [comment] 2015-01-24 20:45
Should now be fixed with this commit e9b0d6b687759d963047680a7e62616884d54feb.
The plugin won't override your mapping. Please let me know if you still have trouble.

**Comment by unphased** [comment] 2015-01-24 20:48
Sweetness. Thanks!

**Comment by unphased** [comment] 2015-02-08 00:38
(Finally) tested, and it works!

**Comment by unphased** [comment] 2018-01-11 20:02
@bruno- I think this doesn't work anymore? It's a regression?

**Comment by bruno-** [comment] 2018-01-12 14:02
Hi,

I made no changes to this since this plugin was originally developed.

**Comment by unphased** [comment] 2018-01-12 18:42
But it seems like this https://github.com/tmux-plugins/vim-tmux/commit/9ead2580b5207fb2130d77a670a6ee934fbb59e6 did?

**Comment by bruno-** [comment] 2018-01-21 21:16
Man .. that was half a year ago and I would swear I didn't commit that. LOL
Do you know what might be a problem with that one?

**Comment by unphased** [comment] 2018-01-21 23:25
Yes. 

The `maparg` produces for me `{'silent': 0, 'noremap': 1, 'lhs': 'K', 'mode': ' ', 'nowait': 0, 'expr': 0, 'sid': 1, 'rhs': '5gk', 'buffer': 0}` and so the logic in 9ead258 seems to say "if K is not bound OR if it is not bound in this buffer, assign K". The second condition holds true, so K becomes overridden for me.

**Comment by bruno-** [comment] 2018-01-22 12:19
Hmm.. it seems we just need to change the OR condition to AND, right?

**Comment by unphased** [comment] 2018-01-22 15:08
Yeah that makes more sense to me... I’ll do the change and give you a pull request!

**Comment by bruno-** [comment] 2018-01-24 12:15
Hey, the PR #20 caused issue #21 that was easily reproducible. I reverted #20 for now.

**Comment by bruno-** [comment] 2018-01-24 12:36
I tested this again and I think we could revert 9ead258 and everything should work fine.

**Comment by unphased** [comment] 2018-01-24 17:32
Interesting! Changing how it short circuits broke older vims? Or something?? 

Confused because 9ead258 was what introduced the check for the buffer field... 

Ok let’s revert 9ead258 then, as you say. I’ll let you do it.

Sorry for breaking stuff

**Comment by bruno-** [comment] 2018-01-27 11:46
Ok reverted.

**Closed as completed** 2018-01-27 11:46 UTC
